export const ApiPaths = {
  HEALTH: "/health",
  AUTH: {
    ADMIN_SIGNIN: "/auth/admin/signin",
    TRAINER_SIGNIN: "/auth/trainer/signin",
    STUDENT_LOGIN: "/auth/student/login",
    STUDENT_UPDATE_PASSWORD: "/auth/student/update-password",
    VERIFY_TOKEN: "/auth/verify-token",
  },
  BRANCH: {
    CREATE: "/api/v1/branch/createBranch",
    GET_ALL: "/api/v1/branch/getAllBranches",
    UPDATE: "/api/v1/branch/updateBranch",
    DELETE: "/api/v1/branch/deleteBranch",
  },
  TRAINER: {
    CREATE: "/api/v1/trainer/createTrainer",
    GET_ALL: "/api/v1/trainer/getAllTrainers",
    GET_BY_ID: "/api/v1/trainer/getTrainerById",
    UPDATE: "/api/v1/trainer/updateTrainer",
    DELETE: "/api/v1/trainer/deleteTrainer",
  },
  COURSES_AND_TOPICS: {
    CREATE_COURSE: "/api/v1/coursesandtopics/createCourse",
    GET_ALL_COURSES: "/api/v1/coursesandtopics/getAllCourses",
    GET_COURSE_BY_ID: "/api/v1/coursesandtopics/getCourseById",
    UPDATE_COURSE: "/api/v1/coursesandtopics/updateCourse",
    DELETE_COURSE: "/api/v1/coursesandtopics/deleteCourse",
    CREATE_TOPIC: "/api/v1/coursesandtopics/createTopic",
    GET_ALL_TOPICS: "/api/v1/coursesandtopics/getAllTopics",
    GET_TOPIC_BY_ID: "/api/v1/coursesandtopics/getTopicById",
    UPDATE_TOPIC: "/api/v1/coursesandtopics/updateTopic",
    DELETE_TOPIC: "/api/v1/coursesandtopics/deleteTopic",
    ASSIGN_TOPICS_TO_COURSE: "/api/v1/coursesandtopics/assignTopicsToCourse",
    GET_COURSE_TOPICS: "/api/v1/coursesandtopics/getCourseTopics",
    ASSIGN_COURSE_TO_STUDENT: "/api/v1/coursesandtopics/assignCourseToStudent",
  },
  STUDENT: {
    CREATE: "/api/v1/student/createStudent",
    GET_ALL: "/api/v1/student/getAllStudents",
    GET_BY_ID: "/api/v1/student/getStudentById",
    UPDATE: "/api/v1/student/updateStudent",
    DELETE: "/api/v1/student/deleteStudent",
    GET_BY_BRANCH: "/api/v1/student/getStudentByBranch",
  },
  BATCH: {
    CREATE: "/api/v1/batch/createBatch",
    GET_ALL: "/api/v1/batch/getAllBatches",
    GET_BY_ID: "/api/v1/batch/getBatchById",
    UPDATE: "/api/v1/batch/updateBatch",
    DELETE: "/api/v1/batch/deleteBatch",
    ASSIGN_TO_STUDENT: "/api/v1/batch/assignBatchToStudent",
    GET_BY_FILTERS: "/api/v1/batch/getBatchesByFilters",
  },
  MATERIAL: {
    CREATE: "/api/v1/material/createMaterial",
    GET_ALL: "/api/v1/material/getAllMaterials",
    GET_BY_ID: "/api/v1/material/getMaterialById",
    UPDATE: "/api/v1/material/updateMaterial",
    DELETE: "/api/v1/material/deleteMaterial",
  },
  DOMAIN: {
    CREATE: "/api/v1/domain/createDomain",
    GET_ALL: "/api/v1/domain/getAllDomains",
    GET_BY_ID: "/api/v1/domain/getDomainById",
    UPDATE: "/api/v1/domain/updateDomain",
    DELETE: "/api/v1/domain/deleteDomain",
  },
};
